string host         # The gripper's TCP/IP host address
uint16 port         # The gripper's TCP/IP port
string serial_port  # The gripper's serial port
uint8 device_id     # The gripper's Modbus device id
---
bool success
string message
