int16 force   # Grip force in percent
              # Depends on the gripper type and if the gripper
              # has a brake
              # For grippers of type EGU/EGK/EZU without brake:
              # 50 ≤ gripping force [%] ≤ 100
              # For grippers of type EGU/EZU with brake:
              # EGU 50, 60, 80, EZU 30, 35, 40: 50 ≤ gripping force [%] ≤ 200
              # EGU 70: 50 ≤ gripping force [%] ≤ 150

bool outward  # Whether to grip the workpiece from the inside
              # (Fingers are moving outwards).
              # Defaults to False.

float32 position  # Expect to grip a workpiece at a specific position in [m]
                  # If an unexpected workpiece was gripped or
                  # the gripping position was exceeded the command is terminated
                  # and the gripper will either set bit 17 (wrong wp gripped) or
                  # bit 11 (no wp gripped) in the statusword.
---

# Flags indicating the outcome of the grip operation.
# If the grip operation failed, all flags below will be False.
# If it succeeded, exactly one of the flags below will be True.
bool workpiece_gripped
bool no_workpiece_detected
bool wrong_workpiece_gripped
bool workpiece_lost

bool success   # Overall success status; False if an error occurred.
string message # Human-readable status or error description.
