string parameter  # Module parameter in hex, e.g. "0x0380"
uint8 length      # Lenght of the parameter to read
---
bool success
string message

# Return types depend on the parameter.
# Only one array will be filled.
byte[] payload    # Received data from the gripper. 
