string instance

---
bool[] bool_value
uint8[] uint8_value
uint16[] uint16_value
uint32[] uint32_value
int32[] int32_value
float32[] float_value
uint8[] enum_value
string[] enum_string
string char_value
