#!/usr/bin/sh

# Default port
port=8000

# Parse arguments
while [ $# -gt 0 ]; do
  case "$1" in
    --ros-args)
      shift
      ;;
    -p|--port)
      shift
      ;;
    port:*)
      port="${1#*:=}"
      shift
      ;;
    *)
      shift
      ;;
  esac
done

uvicorn schunk_gripper_dummy.main:server --port $port --reload
