float32 absolute_position
float32 velocity_of_movement
float32 gripping_force
bool grip_direction
---
float32 absolute_position
bool workpiece_gripped
bool no_workpiece_detected
bool workpiece_lost
bool wrong_workpiece_detected
---
float32 absolute_position
float32 velocity_of_movement
float32 motor_current
bool workpiece_pre_grip_started