float32 max_stroke      # The gripper's maximum stroke in mm
float32 max_speed       # The gripper's maximum speed in mm/s
float32 max_force       # The gripper's maximum force in N
string serial_number    # The gripper's serial number
string firmware_version # The gripper's firmware version
uint8 device_id         # The gripper's device ID (for Modbus grippers)
string ip_address       # The gripper's IP address (for Ethernet-based grippers)
